name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
          cache: "maven"

      - name: Setup directories
        run: |
          BASE_DIR=/var/opt/cprocsp
          sudo mkdir -p $BASE_DIR/tmp
          sudo chmod a+rwx $BASE_DIR/tmp

      - name: Retrieve commit info
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: commit_info

      - name: Build packages
        run: mvn -B -f bom/pom.xml -P "java8,java17" clean verify
