name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'epic'
    tags:
      - 'v*'

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - { os: ubuntu-20.04, arch: "linux/amd64" }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'

      - name: Build packages
        run:  |
          set -xeo pipefail
          
          mvn -B -X -f bom/pom.xml -Drevision="${GITHUB_SHA::7}" -P "java8,java17" clean deploy
          echo "Done."

      - name: Deploy package
        shell: bash
        run: |
          set -xeo pipefail
          
          mvn -B -X -f bom/pom.xml -Drevision="${GITHUB_SHA::7}" -P "java8,java17" clean deploy
          echo "Done."
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}